/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface CheckBundlerInput {
  configPath: string
  compression: string
}
export function checkBundler(input: CheckBundlerInput): void
