/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface AnalyzeResult {
  pass: boolean
  fSize: number
  budgetSize: number
}
export interface CheckBundlerInput {
  configPath: string
  compression: string
}
export interface CheckBundlerOutput {
  result: FxHashMap
}
export function checkBundlerSync(input: CheckBundlerInput): CheckBundlerOutput
