/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface AnalyzeReport {
  pass: boolean
  actualFileSize: number
  sizeUnit: string
  compression: string
  budgetSize: number
  error?: string
}
export interface CheckBundlerInput {
  configPath: string
  compression: string
  reporter: string
}
export interface BundleOutputSummary {
  total: number
  success: number
  fail: number
  error: number
}
export interface CheckBundlerOutput {
  summary: BundleOutputSummary
  result: FxHashMap
}
export function checkBundlerSync(input: CheckBundlerInput): CheckBundlerOutput
